# theme: jekyll-theme-midnight

# ascii art theme! :)
remote_theme: b2a3e8/jekyll-theme-console # jekyll/minima # force remote download to get the most recent version, which has skins

#minima:
#  skin: solarized-dark
