title: experimental game anarchy
descrption: a rad digital communal space for passionate people that <3s e x p e r i m e n t a l games
# theme: jekyll-theme-midnight

# ascii art theme! :)
remote_theme: b2a3e8/jekyll-theme-console # jekyll/minima # force remote download to get the most recent version, which has skins

#minima:
#  skin: solarized-dark

# console theme specific stuff
header_pages: # top nav bar
  - index.md
# - about.md
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'a willowolf of rathewolf'

google_analytics: UA-NNNNNNNN-N
