# ascii art theme! :)
remote_theme: rahil627/console-jekyll-theme-customized #not updated for years! should just use a barebones theme and edit the style file

# standard vars
# these two vars don't exist in jekyll-theme-console, will throw an error!
title: "saturn valley: dao of experimental games"
# description: a rad digital communal space for passionate people that <3s e x p e r i m e n t a l games

# console theme specific stuff
style: dark # dark (default, ascii art game like black 'n white), hacker (console terminal green), light
header_pages: # top nav bar
  - index.md
  - 404.md #lol
# listen_for_clients_preferred_style: true # false (default) or true

footer: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>

# code highlighting
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
